[package]
name = "wamr-runtime-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jlogger-tracing = "0.1.4"

[build-dependencies]
jlogger-tracing = "0.1.4"
